---
name: Facial Age Classification
author: wangyi
description: Facial Age Classification
topic: Facial Age Classification
algorithm: CNN
language: Python3

framework: Keras

data:
  id: FacialAgeTenClass
  name: Facial Age Classification
  category: image


model:
  processor: Processor
  input_x: input_x
  output_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: url
    to_type: float
    to_shape:  [-1,299,299,3]
  output:
    columns:
      - name: label
        type: int
    to_type: int
    to_shape: [-1,10]



servers:
 - id: flyai
   url: https://www.flyai.com
...